name: adaptive_bottom_navigation
description: "A Flutter package that displays an adaptive bottom navigation bar depending on the platform"
homepage: https://github.com/badiniibrahim/adaptive_botton_navigation
repository: https://github.com/badiniibrahim/adaptive_botton_navigation

version: 1.0.5

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_cli: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
